### ISSUE TITLE
Problem when run script

### ISSUE THREAD

**Issue by SlaSerX** [ip-rw/easy4us#5]
clearing pageTraceback (most recent call last):
  File "/home/slaserx/lab/easy4us/main.py", line 159, in <module>
    clear(session)
  File "/home/slaserx/lab/easy4us/main.py", line 61, in clear
    final += "%s&" % urllib.parse.urlencode({i["name"]: i["value"]})
  File "/usr/lib/python3/dist-packages/bs4/element.py", line 1486, in __getitem__
    return self.attrs[key]
KeyError: 'value'

**Comment by ip-rw** [comment]
this is not a bug report. try harder.
