### ISSUE TITLE
Couldn't find a tree builder with the features you requested: lxml

### ISSUE THREAD

**Issue by willdashwood** [ip-rw/easy4us#6]
I'm trying to decode files encoded as IC10.2 PHP 7.2. When I first ran the script I got the following error:

```
Traceback (most recent call last):
  File "/var/www/webroot/easy4us/main.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

Then I saw from another issue on here that running "pip install bs4 requests" might help so I did that. But now I get this error.

```
clearing pageTraceback (most recent call last):
  File "/var/www/webroot/easy4us/main.py", line 159, in <module>
    clear(session)
  File "/var/www/webroot/easy4us/main.py", line 54, in clear
    s = bs4.BeautifulSoup(res.content, features="lxml")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jelastic-python311/lib/python3.11/site-packages/bs4/__init__.py", line 248, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

Am I missing something else? Thanks!

**Comment by willdashwood** [comment]
Should have googled it first! Solved that error with "pip install lxml". However, I now seem to be getting errors from the service.

```
Too many connections!
Please stop brute force ours services.
```
 
Is there a way to throttle requests?

**Comment by simont26** [comment]
@willdashwood I ran the script and now getting access forbidden..
something like this might work to put a delay between files.  I havnt tested

line #135 in main.py

`def process_files(session, dir, dest, phpfiles):
    print("uploading %d files..." % len(phpfiles), end='', flush=True)
    res = upload(session, dir, phpfiles)
    if res:
        success, failure = res
        print("done. %s successful, %d failed." % (len(success), len(failure)))
        # copy(dir, dest, failure)
        not_decoded.extend([os.path.join(dir, f) for f in failure])
        # download zip
        if len(success) > 0:
            if not download_zip(session, dest):
                # print("download failed. refreshing session...", end='')
                # session = login(args.username, args.password)
                # print("done")
                # if not download_zip(session, dest):
                print("couldn't download. copying originals and continuing")
                # copy(dir, dest, phpfiles)
                not_decoded.extend([os.path.join(dir, f) for f in phpfiles])
            clear(session)

    # delay for 5 seconds between files
    time.sleep(5)`

**Comment by simont26** [comment]
you'll need to add 

import time 

to the imports at the start of the file as well

**Comment by sskafandri** [comment]
can you please help me to fix this issue i get this error message : 
clearing pageTraceback (most recent call last):
File "c:\easy4us\main.py", line 159, in
clear(session)
File "c:\easy4us\main.py", line 61, in clear
final += "%s&" % urllib.parse.urlencode({i["name"]: i["value"]})
File "\dist-packages\bs4\element.py", line 1486, in getitem
return self.attrs[key]
KeyError: 'value'

**Comment by ip-rw** [comment]
Thank you for your reports.

I did reach out to the owner of easytoyou.eu when I first pushed this to GitHub... I rather assumed that anything giving him more exposure/sales was a good thing but he never responded... 

I don't have an account at the moment, perhaps if somebody would be willing to share theirs with me I can have a little look to see if anything major has changed.

I've just looked at his site and saw this:

```
Dear easytoyou.eu users,
on 01/03/2023 we will change the prices as well as the period from membership 30 days to membership 7 days
We will be making these changes to stop abuse account sharing Internet forum's 
also to respect competition ioncube service, for prices to be more balanced for both sides.

Thanks for understanding
Administrator EasyToYou.eu
```

Now gentlemen - you haven't by chance been sharing accounts? Decoding IonCube involves hooking into the Zend Engine recovering symbols from various places and then manually recreated the code from the PHP bytecode. This is hard.

Could somebody independent confirm that there have been breaking changes to the site? If so then please speak up and we'll see what we can do to fix it.

I'm also going to message the author and find if he has any issues with what this script does (having read his message I wonder if people are using this to resell his service. I don't want this and won't support it.) 

Thank you for the reports chaps. Remember this is a team effort and none of this is rocket science so feel free to do your own research and post your findings here.

**Comment by willdashwood** [comment]
To be honest, I emailed the guy my zip file and he was happy to decode it all for me. Would be great if it was automated but my 30 days is almost up now.

**Comment by ip-rw** [comment]
> To be honest, I emailed the guy my zip file and he was happy to decode it all for me. 
Well as long as you're alright then I guess we can all go home happy!

> Would be great if it was automated
I feel the same way. Sort of the idea of the script... 

> but my 30 days is almost up now.
You really don't get this spirit of cooperation thing do you :)

Maybe you can have a word with the guy and see if he dislikes this project. Seem's he doesn't like me, I've yet to receive a response from him :)

If he's not against the project then I'll buy a package and fix this for people (not that I even know it's broken, could you check?).

**Comment by willdashwood** [comment]
I'll ask him to take a look at this thread. I'd also want to know if they are happy with this project and if so, would be happy to try and help.

**Comment by ip-rw** [comment]
> I'll ask him to take a look at this thread. I'd also want to know if they are happy with this project and if so, would be happy to try and help.

sorry for my passive aggressive tone :)) my bad i got stuff on my mind :)

**Comment by ip-rw** [comment]
> @ip-rw I used this wrapper last night and my account was instantly IP banned lol. Still no response to my emails. I see they're changing pricing so I hope they don't limit the conversions at the same time

nobody does. i only put this up here because i had occasion to need it. 

let see if the authors come back to one of us. i'm happy to delete repo this if it's causing them trouble.

there's probably a reason they dont simply allow you to upload a zip (amusing archive path fuckary vulns aside)... who knows.

i'd love to talk to the guys who produced easytoyou.eu... what they've done is super cool and every day is a school day...

**Comment by simont26** [comment]
Don't worry lol its all good.  Its maybe just to manage loads that they only allow 1 file at a time.  Everywhere else seems to charge by the file which sucks
